name: publish to npm and gpr on release

on:
  release:
    types: [published]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: 'https://registry.npmjs.org'
      - run: |
          npm install
          PACKAGE_VERSION=$(node -p -e "require('./package.json').version")
          tag=$([[ $PACKAGE_VERSION =~ [0-9]+.[0-9]+.[0-9]+-canary.[0-9]+ ]] && echo "canary" || echo "latest")
          npm publish --access public --tag $tag
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - uses: actions/setup-node@v1
        with:
          registry-url: 'https://npm.pkg.github.com'
      - run: |
          npm install
          PACKAGE_VERSION=$(node -p -e "require('./package.json').version")
          tag=$([[ $PACKAGE_VERSION =~ [0-9]+.[0-9]+.[0-9]+-canary.[0-9]+ ]] && echo "canary" || echo "latest")
          npm publish --tag $tag
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
