name: publish to npm and gpr on release

on:
  push:
    tags: '*'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: primer/publish@master
      - run: npm install -g npm@next
      - run: npm install
      - run: npm publish --access public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          args: '--registry=https://registry.npmjs.org'
      - uses: actions/setup-node@v1
      - run: npm publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          args: '--registry=https://npm.pkg.github.com'
